version: '3.4'

services:
  dotdesk.userpanelbff:
    image: ${DOCKER_REGISTRY-}dotdeskuserpanelbff
    build:
      context: .
      dockerfile: src/DotDesk.UserPanelBFF/Dockerfile
    ports:
      - "5000:8080" # Map container port 8080 to host port 5000 (HTTP)
      - "5001:8081" # Map container port 8081 to host port 5001 (HTTPS)
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_ENVIRONMENT=Development
